openapi: 3.0.0
info:
  title: Sample Api
  version: 1.0.0
  description: Sample Description
servers:
  - url: http://localhost:5050/
    description: Local Server
security:
  - BearerAuth: []

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer